/*
 * ContainerProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.changetypes.OverrideParameter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddDeliveryOptionsHelmDeliveryOptionDetails
 */
@JsonPropertyOrder({
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_DESCRIPTION,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_USAGE_INSTRUCTIONS,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_CONTAINER_IMAGES,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_COMPATIBLE_SERVICES,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_HELM_CHART_URI,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_QUICK_LAUNCH_ENABLED,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_RELEASE_NAME,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_NAMESPACE,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME,
  AddDeliveryOptionsHelmDeliveryOptionDetails.JSON_PROPERTY_OVERRIDE_PARAMETERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AddDeliveryOptionsHelmDeliveryOptionDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private String description;

  public static final String JSON_PROPERTY_USAGE_INSTRUCTIONS = "UsageInstructions";
  private String usageInstructions;

  public static final String JSON_PROPERTY_CONTAINER_IMAGES = "ContainerImages";
  private List<String> containerImages = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPATIBLE_SERVICES = "CompatibleServices";
  private List<String> compatibleServices = new ArrayList<>();

  public static final String JSON_PROPERTY_HELM_CHART_URI = "HelmChartUri";
  private String helmChartUri;

  public static final String JSON_PROPERTY_QUICK_LAUNCH_ENABLED = "QuickLaunchEnabled";
  private Boolean quickLaunchEnabled;

  public static final String JSON_PROPERTY_RELEASE_NAME = "ReleaseName";
  private String releaseName;

  public static final String JSON_PROPERTY_NAMESPACE = "Namespace";
  private String namespace;

  public static final String JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME = "MarketplaceServiceAccountName";
  private String marketplaceServiceAccountName;

  public static final String JSON_PROPERTY_OVERRIDE_PARAMETERS = "OverrideParameters";
  private List<OverrideParameter> overrideParameters;

  public AddDeliveryOptionsHelmDeliveryOptionDetails() {
  }

  public AddDeliveryOptionsHelmDeliveryOptionDetails description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails usageInstructions(String usageInstructions) {
    
    this.usageInstructions = usageInstructions;
    return this;
  }

   /**
   * Get usageInstructions
   * @return usageInstructions
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsageInstructions() {
    return usageInstructions;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsageInstructions(String usageInstructions) {
    this.usageInstructions = usageInstructions;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails containerImages(List<String> containerImages) {
    
    this.containerImages = containerImages;
    return this;
  }

  public AddDeliveryOptionsHelmDeliveryOptionDetails addContainerImagesItem(String containerImagesItem) {
    if (this.containerImages == null) {
      this.containerImages = new ArrayList<>();
    }
    this.containerImages.add(containerImagesItem);
    return this;
  }

   /**
   * Get containerImages
   * @return containerImages
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getContainerImages() {
    return containerImages;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContainerImages(List<String> containerImages) {
    this.containerImages = containerImages;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails compatibleServices(List<String> compatibleServices) {
    
    this.compatibleServices = compatibleServices;
    return this;
  }

  public AddDeliveryOptionsHelmDeliveryOptionDetails addCompatibleServicesItem(String compatibleServicesItem) {
    if (this.compatibleServices == null) {
      this.compatibleServices = new ArrayList<>();
    }
    this.compatibleServices.add(compatibleServicesItem);
    return this;
  }

   /**
   * Get compatibleServices
   * @return compatibleServices
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMPATIBLE_SERVICES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getCompatibleServices() {
    return compatibleServices;
  }


  @JsonProperty(JSON_PROPERTY_COMPATIBLE_SERVICES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompatibleServices(List<String> compatibleServices) {
    this.compatibleServices = compatibleServices;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails helmChartUri(String helmChartUri) {
    
    this.helmChartUri = helmChartUri;
    return this;
  }

   /**
   * Get helmChartUri
   * @return helmChartUri
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HELM_CHART_URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHelmChartUri() {
    return helmChartUri;
  }


  @JsonProperty(JSON_PROPERTY_HELM_CHART_URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHelmChartUri(String helmChartUri) {
    this.helmChartUri = helmChartUri;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails quickLaunchEnabled(Boolean quickLaunchEnabled) {
    
    this.quickLaunchEnabled = quickLaunchEnabled;
    return this;
  }

   /**
   * Get quickLaunchEnabled
   * @return quickLaunchEnabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getQuickLaunchEnabled() {
    return quickLaunchEnabled;
  }


  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuickLaunchEnabled(Boolean quickLaunchEnabled) {
    this.quickLaunchEnabled = quickLaunchEnabled;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails releaseName(String releaseName) {
    
    this.releaseName = releaseName;
    return this;
  }

   /**
   * Get releaseName
   * @return releaseName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELEASE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReleaseName() {
    return releaseName;
  }


  @JsonProperty(JSON_PROPERTY_RELEASE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReleaseName(String releaseName) {
    this.releaseName = releaseName;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails marketplaceServiceAccountName(String marketplaceServiceAccountName) {
    
    this.marketplaceServiceAccountName = marketplaceServiceAccountName;
    return this;
  }

   /**
   * Get marketplaceServiceAccountName
   * @return marketplaceServiceAccountName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMarketplaceServiceAccountName() {
    return marketplaceServiceAccountName;
  }


  @JsonProperty(JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketplaceServiceAccountName(String marketplaceServiceAccountName) {
    this.marketplaceServiceAccountName = marketplaceServiceAccountName;
  }


  public AddDeliveryOptionsHelmDeliveryOptionDetails overrideParameters(List<OverrideParameter> overrideParameters) {
    
    this.overrideParameters = overrideParameters;
    return this;
  }

  public AddDeliveryOptionsHelmDeliveryOptionDetails addOverrideParametersItem(OverrideParameter overrideParametersItem) {
    if (this.overrideParameters == null) {
      this.overrideParameters = new ArrayList<>();
    }
    this.overrideParameters.add(overrideParametersItem);
    return this;
  }

   /**
   * Get overrideParameters
   * @return overrideParameters
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OverrideParameter> getOverrideParameters() {
    return overrideParameters;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideParameters(List<OverrideParameter> overrideParameters) {
    this.overrideParameters = overrideParameters;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddDeliveryOptionsHelmDeliveryOptionDetails addDeliveryOptionsHelmDeliveryOptionDetails = (AddDeliveryOptionsHelmDeliveryOptionDetails) o;
    return Objects.equals(this.description, addDeliveryOptionsHelmDeliveryOptionDetails.description) &&
        Objects.equals(this.usageInstructions, addDeliveryOptionsHelmDeliveryOptionDetails.usageInstructions) &&
        Objects.equals(this.containerImages, addDeliveryOptionsHelmDeliveryOptionDetails.containerImages) &&
        Objects.equals(this.compatibleServices, addDeliveryOptionsHelmDeliveryOptionDetails.compatibleServices) &&
        Objects.equals(this.helmChartUri, addDeliveryOptionsHelmDeliveryOptionDetails.helmChartUri) &&
        Objects.equals(this.quickLaunchEnabled, addDeliveryOptionsHelmDeliveryOptionDetails.quickLaunchEnabled) &&
        Objects.equals(this.releaseName, addDeliveryOptionsHelmDeliveryOptionDetails.releaseName) &&
        Objects.equals(this.namespace, addDeliveryOptionsHelmDeliveryOptionDetails.namespace) &&
        Objects.equals(this.marketplaceServiceAccountName, addDeliveryOptionsHelmDeliveryOptionDetails.marketplaceServiceAccountName) &&
        Objects.equals(this.overrideParameters, addDeliveryOptionsHelmDeliveryOptionDetails.overrideParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, usageInstructions, containerImages, compatibleServices, helmChartUri, quickLaunchEnabled, releaseName, namespace, marketplaceServiceAccountName, overrideParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddDeliveryOptionsHelmDeliveryOptionDetails {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    usageInstructions: ").append(toIndentedString(usageInstructions)).append("\n");
    sb.append("    containerImages: ").append(toIndentedString(containerImages)).append("\n");
    sb.append("    compatibleServices: ").append(toIndentedString(compatibleServices)).append("\n");
    sb.append("    helmChartUri: ").append(toIndentedString(helmChartUri)).append("\n");
    sb.append("    quickLaunchEnabled: ").append(toIndentedString(quickLaunchEnabled)).append("\n");
    sb.append("    releaseName: ").append(toIndentedString(releaseName)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    marketplaceServiceAccountName: ").append(toIndentedString(marketplaceServiceAccountName)).append("\n");
    sb.append("    overrideParameters: ").append(toIndentedString(overrideParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

