/*
 * ContainerProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.changetypes.UpdateDeliveryOptionsEcrDeliveryOptionDetails;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.changetypes.UpdateDeliveryOptionsEksAddOnDeliveryOptionDetails;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.changetypes.UpdateDeliveryOptionsHelmDeliveryOptionDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateDeliveryOptionsDetails
 */
@JsonPropertyOrder({
  UpdateDeliveryOptionsDetails.JSON_PROPERTY_ECR_DELIVERY_OPTION_DETAILS,
  UpdateDeliveryOptionsDetails.JSON_PROPERTY_HELM_DELIVERY_OPTION_DETAILS,
  UpdateDeliveryOptionsDetails.JSON_PROPERTY_EKS_ADD_ON_DELIVERY_OPTION_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateDeliveryOptionsDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ECR_DELIVERY_OPTION_DETAILS = "EcrDeliveryOptionDetails";
  private UpdateDeliveryOptionsEcrDeliveryOptionDetails ecrDeliveryOptionDetails;

  public static final String JSON_PROPERTY_HELM_DELIVERY_OPTION_DETAILS = "HelmDeliveryOptionDetails";
  private UpdateDeliveryOptionsHelmDeliveryOptionDetails helmDeliveryOptionDetails;

  public static final String JSON_PROPERTY_EKS_ADD_ON_DELIVERY_OPTION_DETAILS = "EksAddOnDeliveryOptionDetails";
  private UpdateDeliveryOptionsEksAddOnDeliveryOptionDetails eksAddOnDeliveryOptionDetails;

  public UpdateDeliveryOptionsDetails() {
  }

  public UpdateDeliveryOptionsDetails ecrDeliveryOptionDetails(UpdateDeliveryOptionsEcrDeliveryOptionDetails ecrDeliveryOptionDetails) {
    
    this.ecrDeliveryOptionDetails = ecrDeliveryOptionDetails;
    return this;
  }

   /**
   * Get ecrDeliveryOptionDetails
   * @return ecrDeliveryOptionDetails
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ECR_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateDeliveryOptionsEcrDeliveryOptionDetails getEcrDeliveryOptionDetails() {
    return ecrDeliveryOptionDetails;
  }


  @JsonProperty(JSON_PROPERTY_ECR_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEcrDeliveryOptionDetails(UpdateDeliveryOptionsEcrDeliveryOptionDetails ecrDeliveryOptionDetails) {
    this.ecrDeliveryOptionDetails = ecrDeliveryOptionDetails;
  }


  public UpdateDeliveryOptionsDetails helmDeliveryOptionDetails(UpdateDeliveryOptionsHelmDeliveryOptionDetails helmDeliveryOptionDetails) {
    
    this.helmDeliveryOptionDetails = helmDeliveryOptionDetails;
    return this;
  }

   /**
   * Get helmDeliveryOptionDetails
   * @return helmDeliveryOptionDetails
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HELM_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateDeliveryOptionsHelmDeliveryOptionDetails getHelmDeliveryOptionDetails() {
    return helmDeliveryOptionDetails;
  }


  @JsonProperty(JSON_PROPERTY_HELM_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHelmDeliveryOptionDetails(UpdateDeliveryOptionsHelmDeliveryOptionDetails helmDeliveryOptionDetails) {
    this.helmDeliveryOptionDetails = helmDeliveryOptionDetails;
  }


  public UpdateDeliveryOptionsDetails eksAddOnDeliveryOptionDetails(UpdateDeliveryOptionsEksAddOnDeliveryOptionDetails eksAddOnDeliveryOptionDetails) {
    
    this.eksAddOnDeliveryOptionDetails = eksAddOnDeliveryOptionDetails;
    return this;
  }

   /**
   * Get eksAddOnDeliveryOptionDetails
   * @return eksAddOnDeliveryOptionDetails
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EKS_ADD_ON_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateDeliveryOptionsEksAddOnDeliveryOptionDetails getEksAddOnDeliveryOptionDetails() {
    return eksAddOnDeliveryOptionDetails;
  }


  @JsonProperty(JSON_PROPERTY_EKS_ADD_ON_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEksAddOnDeliveryOptionDetails(UpdateDeliveryOptionsEksAddOnDeliveryOptionDetails eksAddOnDeliveryOptionDetails) {
    this.eksAddOnDeliveryOptionDetails = eksAddOnDeliveryOptionDetails;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDeliveryOptionsDetails updateDeliveryOptionsDetails = (UpdateDeliveryOptionsDetails) o;
    return Objects.equals(this.ecrDeliveryOptionDetails, updateDeliveryOptionsDetails.ecrDeliveryOptionDetails) &&
        Objects.equals(this.helmDeliveryOptionDetails, updateDeliveryOptionsDetails.helmDeliveryOptionDetails) &&
        Objects.equals(this.eksAddOnDeliveryOptionDetails, updateDeliveryOptionsDetails.eksAddOnDeliveryOptionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ecrDeliveryOptionDetails, helmDeliveryOptionDetails, eksAddOnDeliveryOptionDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDeliveryOptionsDetails {\n");
    sb.append("    ecrDeliveryOptionDetails: ").append(toIndentedString(ecrDeliveryOptionDetails)).append("\n");
    sb.append("    helmDeliveryOptionDetails: ").append(toIndentedString(helmDeliveryOptionDetails)).append("\n");
    sb.append("    eksAddOnDeliveryOptionDetails: ").append(toIndentedString(eksAddOnDeliveryOptionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

