/*
 * SaaSProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.AddSaaSUrlDeliveryOptionDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddDeliveryOptionDetails
 */
@JsonPropertyOrder({
  AddDeliveryOptionDetails.JSON_PROPERTY_SAA_S_URL_DELIVERY_OPTION_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AddDeliveryOptionDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SAA_S_URL_DELIVERY_OPTION_DETAILS = "SaaSUrlDeliveryOptionDetails";
  private AddSaaSUrlDeliveryOptionDetails saaSUrlDeliveryOptionDetails;

  public AddDeliveryOptionDetails() {
  }

  public AddDeliveryOptionDetails saaSUrlDeliveryOptionDetails(AddSaaSUrlDeliveryOptionDetails saaSUrlDeliveryOptionDetails) {
    
    this.saaSUrlDeliveryOptionDetails = saaSUrlDeliveryOptionDetails;
    return this;
  }

   /**
   * Get saaSUrlDeliveryOptionDetails
   * @return saaSUrlDeliveryOptionDetails
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SAA_S_URL_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AddSaaSUrlDeliveryOptionDetails getSaaSUrlDeliveryOptionDetails() {
    return saaSUrlDeliveryOptionDetails;
  }


  @JsonProperty(JSON_PROPERTY_SAA_S_URL_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSaaSUrlDeliveryOptionDetails(AddSaaSUrlDeliveryOptionDetails saaSUrlDeliveryOptionDetails) {
    this.saaSUrlDeliveryOptionDetails = saaSUrlDeliveryOptionDetails;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddDeliveryOptionDetails addDeliveryOptionDetails = (AddDeliveryOptionDetails) o;
    return Objects.equals(this.saaSUrlDeliveryOptionDetails, addDeliveryOptionDetails.saaSUrlDeliveryOptionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saaSUrlDeliveryOptionDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddDeliveryOptionDetails {\n");
    sb.append("    saaSUrlDeliveryOptionDetails: ").append(toIndentedString(saaSUrlDeliveryOptionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

