/*
 * SaaSProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.ApiSchema;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.AuthorizationType;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.IntegrationProtocol;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiEndpoint
 */
@JsonPropertyOrder({
  ApiEndpoint.JSON_PROPERTY_NAME,
  ApiEndpoint.JSON_PROPERTY_ENDPOINT_URL,
  ApiEndpoint.JSON_PROPERTY_DESCRIPTION,
  ApiEndpoint.JSON_PROPERTY_AUTHORIZATION_TYPES,
  ApiEndpoint.JSON_PROPERTY_SCHEMAS,
  ApiEndpoint.JSON_PROPERTY_INTEGRATION_PROTOCOLS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class ApiEndpoint implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public static final String JSON_PROPERTY_ENDPOINT_URL = "EndpointUrl";
  private String endpointUrl;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private String description;

  public static final String JSON_PROPERTY_AUTHORIZATION_TYPES = "AuthorizationTypes";
  private List<AuthorizationType> authorizationTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_SCHEMAS = "Schemas";
  private List<ApiSchema> schemas = new ArrayList<>();

  public static final String JSON_PROPERTY_INTEGRATION_PROTOCOLS = "IntegrationProtocols";
  private List<IntegrationProtocol> integrationProtocols = new ArrayList<>();

  public ApiEndpoint() {
  }

  public ApiEndpoint name(String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public ApiEndpoint endpointUrl(String endpointUrl) {
    
    this.endpointUrl = endpointUrl;
    return this;
  }

  /**
   * Get endpointUrl
   * @return endpointUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENDPOINT_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEndpointUrl() {
    return endpointUrl;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpointUrl(String endpointUrl) {
    this.endpointUrl = endpointUrl;
  }

  public ApiEndpoint description(String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  public ApiEndpoint authorizationTypes(List<AuthorizationType> authorizationTypes) {
    
    this.authorizationTypes = authorizationTypes;
    return this;
  }

  public ApiEndpoint addAuthorizationTypesItem(AuthorizationType authorizationTypesItem) {
    if (this.authorizationTypes == null) {
      this.authorizationTypes = new ArrayList<>();
    }
    this.authorizationTypes.add(authorizationTypesItem);
    return this;
  }

  /**
   * Get authorizationTypes
   * @return authorizationTypes
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AUTHORIZATION_TYPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AuthorizationType> getAuthorizationTypes() {
    return authorizationTypes;
  }


  @JsonProperty(JSON_PROPERTY_AUTHORIZATION_TYPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorizationTypes(List<AuthorizationType> authorizationTypes) {
    this.authorizationTypes = authorizationTypes;
  }

  public ApiEndpoint schemas(List<ApiSchema> schemas) {
    
    this.schemas = schemas;
    return this;
  }

  public ApiEndpoint addSchemasItem(ApiSchema schemasItem) {
    if (this.schemas == null) {
      this.schemas = new ArrayList<>();
    }
    this.schemas.add(schemasItem);
    return this;
  }

  /**
   * Get schemas
   * @return schemas
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEMAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ApiSchema> getSchemas() {
    return schemas;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemas(List<ApiSchema> schemas) {
    this.schemas = schemas;
  }

  public ApiEndpoint integrationProtocols(List<IntegrationProtocol> integrationProtocols) {
    
    this.integrationProtocols = integrationProtocols;
    return this;
  }

  public ApiEndpoint addIntegrationProtocolsItem(IntegrationProtocol integrationProtocolsItem) {
    if (this.integrationProtocols == null) {
      this.integrationProtocols = new ArrayList<>();
    }
    this.integrationProtocols.add(integrationProtocolsItem);
    return this;
  }

  /**
   * Get integrationProtocols
   * @return integrationProtocols
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTEGRATION_PROTOCOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IntegrationProtocol> getIntegrationProtocols() {
    return integrationProtocols;
  }


  @JsonProperty(JSON_PROPERTY_INTEGRATION_PROTOCOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntegrationProtocols(List<IntegrationProtocol> integrationProtocols) {
    this.integrationProtocols = integrationProtocols;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiEndpoint apiEndpoint = (ApiEndpoint) o;
    return Objects.equals(this.name, apiEndpoint.name) &&
        Objects.equals(this.endpointUrl, apiEndpoint.endpointUrl) &&
        Objects.equals(this.description, apiEndpoint.description) &&
        Objects.equals(this.authorizationTypes, apiEndpoint.authorizationTypes) &&
        Objects.equals(this.schemas, apiEndpoint.schemas) &&
        Objects.equals(this.integrationProtocols, apiEndpoint.integrationProtocols);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, endpointUrl, description, authorizationTypes, schemas, integrationProtocols);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiEndpoint {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    endpointUrl: ").append(toIndentedString(endpointUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    authorizationTypes: ").append(toIndentedString(authorizationTypes)).append("\n");
    sb.append("    schemas: ").append(toIndentedString(schemas)).append("\n");
    sb.append("    integrationProtocols: ").append(toIndentedString(integrationProtocols)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

