/*
 * SaaSProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.ApiEndpoint;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.ApiType;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.changetypes.CompatibleService;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * One of [ApiType, QuickLaunchEnabled, CompatibleServices, FulfillmentUrl, UsageInstructions, Endpoints] is required
 */
@JsonPropertyOrder({
  UpdateApiDeliveryOptionDetails.JSON_PROPERTY_API_TYPE,
  UpdateApiDeliveryOptionDetails.JSON_PROPERTY_QUICK_LAUNCH_ENABLED,
  UpdateApiDeliveryOptionDetails.JSON_PROPERTY_COMPATIBLE_SERVICES,
  UpdateApiDeliveryOptionDetails.JSON_PROPERTY_FULFILLMENT_URL,
  UpdateApiDeliveryOptionDetails.JSON_PROPERTY_USAGE_INSTRUCTIONS,
  UpdateApiDeliveryOptionDetails.JSON_PROPERTY_ENDPOINTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UpdateApiDeliveryOptionDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_API_TYPE = "ApiType";
  private ApiType apiType;

  public static final String JSON_PROPERTY_QUICK_LAUNCH_ENABLED = "QuickLaunchEnabled";
  private Boolean quickLaunchEnabled;

  public static final String JSON_PROPERTY_COMPATIBLE_SERVICES = "CompatibleServices";
  private List<CompatibleService> compatibleServices = new ArrayList<>();

  public static final String JSON_PROPERTY_FULFILLMENT_URL = "FulfillmentUrl";
  private String fulfillmentUrl;

  public static final String JSON_PROPERTY_USAGE_INSTRUCTIONS = "UsageInstructions";
  private String usageInstructions;

  public static final String JSON_PROPERTY_ENDPOINTS = "Endpoints";
  private List<ApiEndpoint> endpoints = new ArrayList<>();

  public UpdateApiDeliveryOptionDetails() {
  }

  public UpdateApiDeliveryOptionDetails apiType(ApiType apiType) {
    
    this.apiType = apiType;
    return this;
  }

  /**
   * Get apiType
   * @return apiType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ApiType getApiType() {
    return apiType;
  }


  @JsonProperty(JSON_PROPERTY_API_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiType(ApiType apiType) {
    this.apiType = apiType;
  }

  public UpdateApiDeliveryOptionDetails quickLaunchEnabled(Boolean quickLaunchEnabled) {
    
    this.quickLaunchEnabled = quickLaunchEnabled;
    return this;
  }

  /**
   * Get quickLaunchEnabled
   * @return quickLaunchEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getQuickLaunchEnabled() {
    return quickLaunchEnabled;
  }


  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuickLaunchEnabled(Boolean quickLaunchEnabled) {
    this.quickLaunchEnabled = quickLaunchEnabled;
  }

  public UpdateApiDeliveryOptionDetails compatibleServices(List<CompatibleService> compatibleServices) {
    
    this.compatibleServices = compatibleServices;
    return this;
  }

  public UpdateApiDeliveryOptionDetails addCompatibleServicesItem(CompatibleService compatibleServicesItem) {
    if (this.compatibleServices == null) {
      this.compatibleServices = new ArrayList<>();
    }
    this.compatibleServices.add(compatibleServicesItem);
    return this;
  }

  /**
   * Get compatibleServices
   * @return compatibleServices
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPATIBLE_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CompatibleService> getCompatibleServices() {
    return compatibleServices;
  }


  @JsonProperty(JSON_PROPERTY_COMPATIBLE_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompatibleServices(List<CompatibleService> compatibleServices) {
    this.compatibleServices = compatibleServices;
  }

  public UpdateApiDeliveryOptionDetails fulfillmentUrl(String fulfillmentUrl) {
    
    this.fulfillmentUrl = fulfillmentUrl;
    return this;
  }

  /**
   * Get fulfillmentUrl
   * @return fulfillmentUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULFILLMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFulfillmentUrl() {
    return fulfillmentUrl;
  }


  @JsonProperty(JSON_PROPERTY_FULFILLMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFulfillmentUrl(String fulfillmentUrl) {
    this.fulfillmentUrl = fulfillmentUrl;
  }

  public UpdateApiDeliveryOptionDetails usageInstructions(String usageInstructions) {
    
    this.usageInstructions = usageInstructions;
    return this;
  }

  /**
   * Get usageInstructions
   * @return usageInstructions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsageInstructions() {
    return usageInstructions;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsageInstructions(String usageInstructions) {
    this.usageInstructions = usageInstructions;
  }

  public UpdateApiDeliveryOptionDetails endpoints(List<ApiEndpoint> endpoints) {
    
    this.endpoints = endpoints;
    return this;
  }

  public UpdateApiDeliveryOptionDetails addEndpointsItem(ApiEndpoint endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

  /**
   * Get endpoints
   * @return endpoints
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ApiEndpoint> getEndpoints() {
    return endpoints;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoints(List<ApiEndpoint> endpoints) {
    this.endpoints = endpoints;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApiDeliveryOptionDetails updateApiDeliveryOptionDetails = (UpdateApiDeliveryOptionDetails) o;
    return Objects.equals(this.apiType, updateApiDeliveryOptionDetails.apiType) &&
        Objects.equals(this.quickLaunchEnabled, updateApiDeliveryOptionDetails.quickLaunchEnabled) &&
        Objects.equals(this.compatibleServices, updateApiDeliveryOptionDetails.compatibleServices) &&
        Objects.equals(this.fulfillmentUrl, updateApiDeliveryOptionDetails.fulfillmentUrl) &&
        Objects.equals(this.usageInstructions, updateApiDeliveryOptionDetails.usageInstructions) &&
        Objects.equals(this.endpoints, updateApiDeliveryOptionDetails.endpoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiType, quickLaunchEnabled, compatibleServices, fulfillmentUrl, usageInstructions, endpoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApiDeliveryOptionDetails {\n");
    sb.append("    apiType: ").append(toIndentedString(apiType)).append("\n");
    sb.append("    quickLaunchEnabled: ").append(toIndentedString(quickLaunchEnabled)).append("\n");
    sb.append("    compatibleServices: ").append(toIndentedString(compatibleServices)).append("\n");
    sb.append("    fulfillmentUrl: ").append(toIndentedString(fulfillmentUrl)).append("\n");
    sb.append("    usageInstructions: ").append(toIndentedString(usageInstructions)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

