/*
 * MachineLearningProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SageMakerModelPackageRecommendedInstanceTypes
 */
@JsonPropertyOrder({
  SageMakerModelPackageRecommendedInstanceTypes.JSON_PROPERTY_BATCH_TRANSFORM,
  SageMakerModelPackageRecommendedInstanceTypes.JSON_PROPERTY_REALTIME_INFERENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class SageMakerModelPackageRecommendedInstanceTypes implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BATCH_TRANSFORM = "BatchTransform";
  private String batchTransform;

  public static final String JSON_PROPERTY_REALTIME_INFERENCE = "RealtimeInference";
  private String realtimeInference;

  public SageMakerModelPackageRecommendedInstanceTypes() {
  }

  public SageMakerModelPackageRecommendedInstanceTypes batchTransform(String batchTransform) {
    
    this.batchTransform = batchTransform;
    return this;
  }

  /**
   * Get batchTransform
   * @return batchTransform
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBatchTransform() {
    return batchTransform;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchTransform(String batchTransform) {
    this.batchTransform = batchTransform;
  }

  public SageMakerModelPackageRecommendedInstanceTypes realtimeInference(String realtimeInference) {
    
    this.realtimeInference = realtimeInference;
    return this;
  }

  /**
   * Get realtimeInference
   * @return realtimeInference
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRealtimeInference() {
    return realtimeInference;
  }


  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRealtimeInference(String realtimeInference) {
    this.realtimeInference = realtimeInference;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SageMakerModelPackageRecommendedInstanceTypes sageMakerModelPackageRecommendedInstanceTypes = (SageMakerModelPackageRecommendedInstanceTypes) o;
    return Objects.equals(this.batchTransform, sageMakerModelPackageRecommendedInstanceTypes.batchTransform) &&
        Objects.equals(this.realtimeInference, sageMakerModelPackageRecommendedInstanceTypes.realtimeInference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchTransform, realtimeInference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SageMakerModelPackageRecommendedInstanceTypes {\n");
    sb.append("    batchTransform: ").append(toIndentedString(batchTransform)).append("\n");
    sb.append("    realtimeInference: ").append(toIndentedString(realtimeInference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

