/*
 * MachineLearningProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Sample
 */
@JsonPropertyOrder({
  Sample.JSON_PROPERTY_REALTIME_INFERENCE_TEXT,
  Sample.JSON_PROPERTY_REALTIME_INFERENCE_URL,
  Sample.JSON_PROPERTY_BATCH_TRANSFORM_TEXT,
  Sample.JSON_PROPERTY_BATCH_TRANSFORM_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class Sample implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_REALTIME_INFERENCE_TEXT = "RealtimeInferenceText";
  private String realtimeInferenceText;

  public static final String JSON_PROPERTY_REALTIME_INFERENCE_URL = "RealtimeInferenceUrl";
  private String realtimeInferenceUrl;

  public static final String JSON_PROPERTY_BATCH_TRANSFORM_TEXT = "BatchTransformText";
  private String batchTransformText;

  public static final String JSON_PROPERTY_BATCH_TRANSFORM_URL = "BatchTransformUrl";
  private String batchTransformUrl;

  public Sample() {
  }

  public Sample realtimeInferenceText(String realtimeInferenceText) {
    
    this.realtimeInferenceText = realtimeInferenceText;
    return this;
  }

  /**
   * Get realtimeInferenceText
   * @return realtimeInferenceText
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRealtimeInferenceText() {
    return realtimeInferenceText;
  }


  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRealtimeInferenceText(String realtimeInferenceText) {
    this.realtimeInferenceText = realtimeInferenceText;
  }

  public Sample realtimeInferenceUrl(String realtimeInferenceUrl) {
    
    this.realtimeInferenceUrl = realtimeInferenceUrl;
    return this;
  }

  /**
   * Get realtimeInferenceUrl
   * @return realtimeInferenceUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRealtimeInferenceUrl() {
    return realtimeInferenceUrl;
  }


  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRealtimeInferenceUrl(String realtimeInferenceUrl) {
    this.realtimeInferenceUrl = realtimeInferenceUrl;
  }

  public Sample batchTransformText(String batchTransformText) {
    
    this.batchTransformText = batchTransformText;
    return this;
  }

  /**
   * Get batchTransformText
   * @return batchTransformText
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBatchTransformText() {
    return batchTransformText;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchTransformText(String batchTransformText) {
    this.batchTransformText = batchTransformText;
  }

  public Sample batchTransformUrl(String batchTransformUrl) {
    
    this.batchTransformUrl = batchTransformUrl;
    return this;
  }

  /**
   * Get batchTransformUrl
   * @return batchTransformUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBatchTransformUrl() {
    return batchTransformUrl;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchTransformUrl(String batchTransformUrl) {
    this.batchTransformUrl = batchTransformUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sample sample = (Sample) o;
    return Objects.equals(this.realtimeInferenceText, sample.realtimeInferenceText) &&
        Objects.equals(this.realtimeInferenceUrl, sample.realtimeInferenceUrl) &&
        Objects.equals(this.batchTransformText, sample.batchTransformText) &&
        Objects.equals(this.batchTransformUrl, sample.batchTransformUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(realtimeInferenceText, realtimeInferenceUrl, batchTransformText, batchTransformUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sample {\n");
    sb.append("    realtimeInferenceText: ").append(toIndentedString(realtimeInferenceText)).append("\n");
    sb.append("    realtimeInferenceUrl: ").append(toIndentedString(realtimeInferenceUrl)).append("\n");
    sb.append("    batchTransformText: ").append(toIndentedString(batchTransformText)).append("\n");
    sb.append("    batchTransformUrl: ").append(toIndentedString(batchTransformUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

