/*
 * MachineLearningProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes.UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes.UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateDeliveryOptionsDetails
 */
@JsonPropertyOrder({
  UpdateDeliveryOptionsDetails.JSON_PROPERTY_SAGE_MAKER_MODEL_PACKAGE_DELIVERY_OPTION_DETAILS,
  UpdateDeliveryOptionsDetails.JSON_PROPERTY_SAGE_MAKER_ALGORITHM_DELIVERY_OPTION_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UpdateDeliveryOptionsDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SAGE_MAKER_MODEL_PACKAGE_DELIVERY_OPTION_DETAILS = "SageMakerModelPackageDeliveryOptionDetails";
  private UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails sageMakerModelPackageDeliveryOptionDetails;

  public static final String JSON_PROPERTY_SAGE_MAKER_ALGORITHM_DELIVERY_OPTION_DETAILS = "SageMakerAlgorithmDeliveryOptionDetails";
  private UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails sageMakerAlgorithmDeliveryOptionDetails;

  public UpdateDeliveryOptionsDetails() {
  }

  public UpdateDeliveryOptionsDetails sageMakerModelPackageDeliveryOptionDetails(UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails sageMakerModelPackageDeliveryOptionDetails) {
    
    this.sageMakerModelPackageDeliveryOptionDetails = sageMakerModelPackageDeliveryOptionDetails;
    return this;
  }

  /**
   * Get sageMakerModelPackageDeliveryOptionDetails
   * @return sageMakerModelPackageDeliveryOptionDetails
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAGE_MAKER_MODEL_PACKAGE_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails getSageMakerModelPackageDeliveryOptionDetails() {
    return sageMakerModelPackageDeliveryOptionDetails;
  }


  @JsonProperty(JSON_PROPERTY_SAGE_MAKER_MODEL_PACKAGE_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSageMakerModelPackageDeliveryOptionDetails(UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails sageMakerModelPackageDeliveryOptionDetails) {
    this.sageMakerModelPackageDeliveryOptionDetails = sageMakerModelPackageDeliveryOptionDetails;
  }

  public UpdateDeliveryOptionsDetails sageMakerAlgorithmDeliveryOptionDetails(UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails sageMakerAlgorithmDeliveryOptionDetails) {
    
    this.sageMakerAlgorithmDeliveryOptionDetails = sageMakerAlgorithmDeliveryOptionDetails;
    return this;
  }

  /**
   * Get sageMakerAlgorithmDeliveryOptionDetails
   * @return sageMakerAlgorithmDeliveryOptionDetails
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAGE_MAKER_ALGORITHM_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails getSageMakerAlgorithmDeliveryOptionDetails() {
    return sageMakerAlgorithmDeliveryOptionDetails;
  }


  @JsonProperty(JSON_PROPERTY_SAGE_MAKER_ALGORITHM_DELIVERY_OPTION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSageMakerAlgorithmDeliveryOptionDetails(UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails sageMakerAlgorithmDeliveryOptionDetails) {
    this.sageMakerAlgorithmDeliveryOptionDetails = sageMakerAlgorithmDeliveryOptionDetails;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDeliveryOptionsDetails updateDeliveryOptionsDetails = (UpdateDeliveryOptionsDetails) o;
    return Objects.equals(this.sageMakerModelPackageDeliveryOptionDetails, updateDeliveryOptionsDetails.sageMakerModelPackageDeliveryOptionDetails) &&
        Objects.equals(this.sageMakerAlgorithmDeliveryOptionDetails, updateDeliveryOptionsDetails.sageMakerAlgorithmDeliveryOptionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sageMakerModelPackageDeliveryOptionDetails, sageMakerAlgorithmDeliveryOptionDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDeliveryOptionsDetails {\n");
    sb.append("    sageMakerModelPackageDeliveryOptionDetails: ").append(toIndentedString(sageMakerModelPackageDeliveryOptionDetails)).append("\n");
    sb.append("    sageMakerAlgorithmDeliveryOptionDetails: ").append(toIndentedString(sageMakerAlgorithmDeliveryOptionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

