/*
 * MachineLearningProduct_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes.InputProperties;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes.OutputProperties;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.changetypes.SageMakerModelPackageRecommendedInstanceTypes;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails
 */
@JsonPropertyOrder({
  UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.JSON_PROPERTY_USAGE_INSTRUCTIONS,
  UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.JSON_PROPERTY_SAMPLE_NOTEBOOK_URL,
  UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.JSON_PROPERTY_REPOSITORY_URL,
  UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.JSON_PROPERTY_INPUT_PROPERTIES,
  UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.JSON_PROPERTY_OUTPUT_PROPERTIES,
  UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.JSON_PROPERTY_RECOMMENDED_INSTANCE_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USAGE_INSTRUCTIONS = "UsageInstructions";
  private String usageInstructions;

  public static final String JSON_PROPERTY_SAMPLE_NOTEBOOK_URL = "SampleNotebookUrl";
  private String sampleNotebookUrl;

  public static final String JSON_PROPERTY_REPOSITORY_URL = "RepositoryUrl";
  private String repositoryUrl;

  public static final String JSON_PROPERTY_INPUT_PROPERTIES = "InputProperties";
  private InputProperties inputProperties;

  public static final String JSON_PROPERTY_OUTPUT_PROPERTIES = "OutputProperties";
  private OutputProperties outputProperties;

  public static final String JSON_PROPERTY_RECOMMENDED_INSTANCE_TYPES = "RecommendedInstanceTypes";
  private SageMakerModelPackageRecommendedInstanceTypes recommendedInstanceTypes;

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails() {
  }

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails usageInstructions(String usageInstructions) {
    
    this.usageInstructions = usageInstructions;
    return this;
  }

  /**
   * Get usageInstructions
   * @return usageInstructions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsageInstructions() {
    return usageInstructions;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsageInstructions(String usageInstructions) {
    this.usageInstructions = usageInstructions;
  }

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails sampleNotebookUrl(String sampleNotebookUrl) {
    
    this.sampleNotebookUrl = sampleNotebookUrl;
    return this;
  }

  /**
   * Get sampleNotebookUrl
   * @return sampleNotebookUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLE_NOTEBOOK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSampleNotebookUrl() {
    return sampleNotebookUrl;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLE_NOTEBOOK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleNotebookUrl(String sampleNotebookUrl) {
    this.sampleNotebookUrl = sampleNotebookUrl;
  }

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails repositoryUrl(String repositoryUrl) {
    
    this.repositoryUrl = repositoryUrl;
    return this;
  }

  /**
   * Get repositoryUrl
   * @return repositoryUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPOSITORY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRepositoryUrl() {
    return repositoryUrl;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepositoryUrl(String repositoryUrl) {
    this.repositoryUrl = repositoryUrl;
  }

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails inputProperties(InputProperties inputProperties) {
    
    this.inputProperties = inputProperties;
    return this;
  }

  /**
   * Get inputProperties
   * @return inputProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InputProperties getInputProperties() {
    return inputProperties;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputProperties(InputProperties inputProperties) {
    this.inputProperties = inputProperties;
  }

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails outputProperties(OutputProperties outputProperties) {
    
    this.outputProperties = outputProperties;
    return this;
  }

  /**
   * Get outputProperties
   * @return outputProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OutputProperties getOutputProperties() {
    return outputProperties;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputProperties(OutputProperties outputProperties) {
    this.outputProperties = outputProperties;
  }

  public UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails recommendedInstanceTypes(SageMakerModelPackageRecommendedInstanceTypes recommendedInstanceTypes) {
    
    this.recommendedInstanceTypes = recommendedInstanceTypes;
    return this;
  }

  /**
   * Get recommendedInstanceTypes
   * @return recommendedInstanceTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECOMMENDED_INSTANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SageMakerModelPackageRecommendedInstanceTypes getRecommendedInstanceTypes() {
    return recommendedInstanceTypes;
  }


  @JsonProperty(JSON_PROPERTY_RECOMMENDED_INSTANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecommendedInstanceTypes(SageMakerModelPackageRecommendedInstanceTypes recommendedInstanceTypes) {
    this.recommendedInstanceTypes = recommendedInstanceTypes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails = (UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails) o;
    return Objects.equals(this.usageInstructions, updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.usageInstructions) &&
        Objects.equals(this.sampleNotebookUrl, updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.sampleNotebookUrl) &&
        Objects.equals(this.repositoryUrl, updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.repositoryUrl) &&
        Objects.equals(this.inputProperties, updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.inputProperties) &&
        Objects.equals(this.outputProperties, updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.outputProperties) &&
        Objects.equals(this.recommendedInstanceTypes, updateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails.recommendedInstanceTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usageInstructions, sampleNotebookUrl, repositoryUrl, inputProperties, outputProperties, recommendedInstanceTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDeliveryOptionsSageMakerModelPackageDeliveryOptionDetails {\n");
    sb.append("    usageInstructions: ").append(toIndentedString(usageInstructions)).append("\n");
    sb.append("    sampleNotebookUrl: ").append(toIndentedString(sampleNotebookUrl)).append("\n");
    sb.append("    repositoryUrl: ").append(toIndentedString(repositoryUrl)).append("\n");
    sb.append("    inputProperties: ").append(toIndentedString(inputProperties)).append("\n");
    sb.append("    outputProperties: ").append(toIndentedString(outputProperties)).append("\n");
    sb.append("    recommendedInstanceTypes: ").append(toIndentedString(recommendedInstanceTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

