/*
 * SaaSProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiSchema
 */
@JsonPropertyOrder({
  ApiSchema.JSON_PROPERTY_TYPE,
  ApiSchema.JSON_PROPERTY_SCHEMA_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class ApiSchema implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TYPE = "Type";
  private String type;

  public static final String JSON_PROPERTY_SCHEMA_URL = "SchemaUrl";
  private String schemaUrl;

  public ApiSchema() {
  }

  public ApiSchema type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }

  public ApiSchema schemaUrl(String schemaUrl) {
    
    this.schemaUrl = schemaUrl;
    return this;
  }

  /**
   * Get schemaUrl
   * @return schemaUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEMA_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaUrl() {
    return schemaUrl;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaUrl(String schemaUrl) {
    this.schemaUrl = schemaUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSchema apiSchema = (ApiSchema) o;
    return Objects.equals(this.type, apiSchema.type) &&
        Objects.equals(this.schemaUrl, apiSchema.schemaUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, schemaUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSchema {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    schemaUrl: ").append(toIndentedString(schemaUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

