/*
 * SaaSProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.entitytype.DeploymentTemplate;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.entitytype.Targeting;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeliveryOption
 */
@JsonPropertyOrder({
  DeliveryOption.JSON_PROPERTY_ID,
  DeliveryOption.JSON_PROPERTY_TYPE,
  DeliveryOption.JSON_PROPERTY_FULFILLMENT_URL,
  DeliveryOption.JSON_PROPERTY_QUICK_LAUNCH_ENABLED,
  DeliveryOption.JSON_PROPERTY_LAUNCH_URL,
  DeliveryOption.JSON_PROPERTY_DEPLOYMENT_TEMPLATES,
  DeliveryOption.JSON_PROPERTY_USAGE_INSTRUCTIONS,
  DeliveryOption.JSON_PROPERTY_VISIBILITY,
  DeliveryOption.JSON_PROPERTY_TARGETING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeliveryOption implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "Id";
  private String id;

  public static final String JSON_PROPERTY_TYPE = "Type";
  private String type;

  public static final String JSON_PROPERTY_FULFILLMENT_URL = "FulfillmentUrl";
  private String fulfillmentUrl;

  public static final String JSON_PROPERTY_QUICK_LAUNCH_ENABLED = "QuickLaunchEnabled";
  private Boolean quickLaunchEnabled;

  public static final String JSON_PROPERTY_LAUNCH_URL = "LaunchUrl";
  private String launchUrl;

  public static final String JSON_PROPERTY_DEPLOYMENT_TEMPLATES = "DeploymentTemplates";
  private List<DeploymentTemplate> deploymentTemplates;

  public static final String JSON_PROPERTY_USAGE_INSTRUCTIONS = "UsageInstructions";
  private String usageInstructions;

  public static final String JSON_PROPERTY_VISIBILITY = "Visibility";
  private String visibility;

  public static final String JSON_PROPERTY_TARGETING = "Targeting";
  private Targeting targeting;

  public DeliveryOption() {
  }

  public DeliveryOption id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public DeliveryOption type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public DeliveryOption fulfillmentUrl(String fulfillmentUrl) {
    
    this.fulfillmentUrl = fulfillmentUrl;
    return this;
  }

   /**
   * Get fulfillmentUrl
   * @return fulfillmentUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULFILLMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFulfillmentUrl() {
    return fulfillmentUrl;
  }


  @JsonProperty(JSON_PROPERTY_FULFILLMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFulfillmentUrl(String fulfillmentUrl) {
    this.fulfillmentUrl = fulfillmentUrl;
  }


  public DeliveryOption quickLaunchEnabled(Boolean quickLaunchEnabled) {
    
    this.quickLaunchEnabled = quickLaunchEnabled;
    return this;
  }

   /**
   * Get quickLaunchEnabled
   * @return quickLaunchEnabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getQuickLaunchEnabled() {
    return quickLaunchEnabled;
  }


  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuickLaunchEnabled(Boolean quickLaunchEnabled) {
    this.quickLaunchEnabled = quickLaunchEnabled;
  }


  public DeliveryOption launchUrl(String launchUrl) {
    
    this.launchUrl = launchUrl;
    return this;
  }

   /**
   * Get launchUrl
   * @return launchUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCH_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLaunchUrl() {
    return launchUrl;
  }


  @JsonProperty(JSON_PROPERTY_LAUNCH_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLaunchUrl(String launchUrl) {
    this.launchUrl = launchUrl;
  }


  public DeliveryOption deploymentTemplates(List<DeploymentTemplate> deploymentTemplates) {
    
    this.deploymentTemplates = deploymentTemplates;
    return this;
  }

  public DeliveryOption addDeploymentTemplatesItem(DeploymentTemplate deploymentTemplatesItem) {
    if (this.deploymentTemplates == null) {
      this.deploymentTemplates = new ArrayList<>();
    }
    this.deploymentTemplates.add(deploymentTemplatesItem);
    return this;
  }

   /**
   * Get deploymentTemplates
   * @return deploymentTemplates
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DeploymentTemplate> getDeploymentTemplates() {
    return deploymentTemplates;
  }


  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeploymentTemplates(List<DeploymentTemplate> deploymentTemplates) {
    this.deploymentTemplates = deploymentTemplates;
  }


  public DeliveryOption usageInstructions(String usageInstructions) {
    
    this.usageInstructions = usageInstructions;
    return this;
  }

   /**
   * Get usageInstructions
   * @return usageInstructions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsageInstructions() {
    return usageInstructions;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsageInstructions(String usageInstructions) {
    this.usageInstructions = usageInstructions;
  }


  public DeliveryOption visibility(String visibility) {
    
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibility() {
    return visibility;
  }


  @JsonProperty(JSON_PROPERTY_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibility(String visibility) {
    this.visibility = visibility;
  }


  public DeliveryOption targeting(Targeting targeting) {
    
    this.targeting = targeting;
    return this;
  }

   /**
   * Get targeting
   * @return targeting
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGETING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Targeting getTargeting() {
    return targeting;
  }


  @JsonProperty(JSON_PROPERTY_TARGETING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargeting(Targeting targeting) {
    this.targeting = targeting;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryOption deliveryOption = (DeliveryOption) o;
    return Objects.equals(this.id, deliveryOption.id) &&
        Objects.equals(this.type, deliveryOption.type) &&
        Objects.equals(this.fulfillmentUrl, deliveryOption.fulfillmentUrl) &&
        Objects.equals(this.quickLaunchEnabled, deliveryOption.quickLaunchEnabled) &&
        Objects.equals(this.launchUrl, deliveryOption.launchUrl) &&
        Objects.equals(this.deploymentTemplates, deliveryOption.deploymentTemplates) &&
        Objects.equals(this.usageInstructions, deliveryOption.usageInstructions) &&
        Objects.equals(this.visibility, deliveryOption.visibility) &&
        Objects.equals(this.targeting, deliveryOption.targeting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, fulfillmentUrl, quickLaunchEnabled, launchUrl, deploymentTemplates, usageInstructions, visibility, targeting);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryOption {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    fulfillmentUrl: ").append(toIndentedString(fulfillmentUrl)).append("\n");
    sb.append("    quickLaunchEnabled: ").append(toIndentedString(quickLaunchEnabled)).append("\n");
    sb.append("    launchUrl: ").append(toIndentedString(launchUrl)).append("\n");
    sb.append("    deploymentTemplates: ").append(toIndentedString(deploymentTemplates)).append("\n");
    sb.append("    usageInstructions: ").append(toIndentedString(usageInstructions)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    targeting: ").append(toIndentedString(targeting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

