/*
 * AmiProduct_1_0
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.amiproduct_1_0;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestrictInstanceTypesChangeDetail
 */
@JsonPropertyOrder({
  RestrictInstanceTypesChangeDetail.JSON_PROPERTY_INSTANCE_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RestrictInstanceTypesChangeDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_INSTANCE_TYPES = "InstanceTypes";
  private Set<String> instanceTypes = new LinkedHashSet<>();

  public RestrictInstanceTypesChangeDetail() {
  }

  public RestrictInstanceTypesChangeDetail instanceTypes(Set<String> instanceTypes) {
    
    this.instanceTypes = instanceTypes;
    return this;
  }

  public RestrictInstanceTypesChangeDetail addInstanceTypesItem(String instanceTypesItem) {
    if (this.instanceTypes == null) {
      this.instanceTypes = new LinkedHashSet<>();
    }
    this.instanceTypes.add(instanceTypesItem);
    return this;
  }

   /**
   * Get instanceTypes
   * @return instanceTypes
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INSTANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<String> getInstanceTypes() {
    return instanceTypes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_INSTANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstanceTypes(Set<String> instanceTypes) {
    this.instanceTypes = instanceTypes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestrictInstanceTypesChangeDetail restrictInstanceTypesChangeDetail = (RestrictInstanceTypesChangeDetail) o;
    return Objects.equals(this.instanceTypes, restrictInstanceTypesChangeDetail.instanceTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestrictInstanceTypesChangeDetail {\n");
    sb.append("    instanceTypes: ").append(toIndentedString(instanceTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

