/*
 * MachineLearningProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype.Parameter;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype.Sample;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InputProperties
 */
@JsonPropertyOrder({
  InputProperties.JSON_PROPERTY_DESCRIPTION,
  InputProperties.JSON_PROPERTY_LIMITATIONS,
  InputProperties.JSON_PROPERTY_SAMPLE_INPUT,
  InputProperties.JSON_PROPERTY_PARAMETERS,
  InputProperties.JSON_PROPERTY_SAGE_MAKER_CUSTOM_ATTRIBUTES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class InputProperties implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private String description;

  public static final String JSON_PROPERTY_LIMITATIONS = "Limitations";
  private String limitations;

  public static final String JSON_PROPERTY_SAMPLE_INPUT = "SampleInput";
  private Sample sampleInput;

  public static final String JSON_PROPERTY_PARAMETERS = "Parameters";
  private List<Parameter> parameters = new ArrayList<>();

  public static final String JSON_PROPERTY_SAGE_MAKER_CUSTOM_ATTRIBUTES = "SageMakerCustomAttributes";
  private List<Parameter> sageMakerCustomAttributes = new ArrayList<>();

  public InputProperties() {
  }

  public InputProperties description(String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  public InputProperties limitations(String limitations) {
    
    this.limitations = limitations;
    return this;
  }

  /**
   * Get limitations
   * @return limitations
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIMITATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLimitations() {
    return limitations;
  }


  @JsonProperty(JSON_PROPERTY_LIMITATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimitations(String limitations) {
    this.limitations = limitations;
  }

  public InputProperties sampleInput(Sample sampleInput) {
    
    this.sampleInput = sampleInput;
    return this;
  }

  /**
   * Get sampleInput
   * @return sampleInput
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLE_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Sample getSampleInput() {
    return sampleInput;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLE_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleInput(Sample sampleInput) {
    this.sampleInput = sampleInput;
  }

  public InputProperties parameters(List<Parameter> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public InputProperties addParametersItem(Parameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Parameter> getParameters() {
    return parameters;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameters(List<Parameter> parameters) {
    this.parameters = parameters;
  }

  public InputProperties sageMakerCustomAttributes(List<Parameter> sageMakerCustomAttributes) {
    
    this.sageMakerCustomAttributes = sageMakerCustomAttributes;
    return this;
  }

  public InputProperties addSageMakerCustomAttributesItem(Parameter sageMakerCustomAttributesItem) {
    if (this.sageMakerCustomAttributes == null) {
      this.sageMakerCustomAttributes = new ArrayList<>();
    }
    this.sageMakerCustomAttributes.add(sageMakerCustomAttributesItem);
    return this;
  }

  /**
   * Get sageMakerCustomAttributes
   * @return sageMakerCustomAttributes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAGE_MAKER_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Parameter> getSageMakerCustomAttributes() {
    return sageMakerCustomAttributes;
  }


  @JsonProperty(JSON_PROPERTY_SAGE_MAKER_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSageMakerCustomAttributes(List<Parameter> sageMakerCustomAttributes) {
    this.sageMakerCustomAttributes = sageMakerCustomAttributes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputProperties inputProperties = (InputProperties) o;
    return Objects.equals(this.description, inputProperties.description) &&
        Objects.equals(this.limitations, inputProperties.limitations) &&
        Objects.equals(this.sampleInput, inputProperties.sampleInput) &&
        Objects.equals(this.parameters, inputProperties.parameters) &&
        Objects.equals(this.sageMakerCustomAttributes, inputProperties.sageMakerCustomAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, limitations, sampleInput, parameters, sageMakerCustomAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputProperties {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    limitations: ").append(toIndentedString(limitations)).append("\n");
    sb.append("    sampleInput: ").append(toIndentedString(sampleInput)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    sageMakerCustomAttributes: ").append(toIndentedString(sageMakerCustomAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

