/*
 * MachineLearningProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype.InputProperties;
import com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype.OutputProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Instructions
 */
@JsonPropertyOrder({
  Instructions.JSON_PROPERTY_USAGE,
  Instructions.JSON_PROPERTY_SAMPLE_NOTEBOOK_URL,
  Instructions.JSON_PROPERTY_REPOSITORY_URL,
  Instructions.JSON_PROPERTY_INPUT_PROPERTIES,
  Instructions.JSON_PROPERTY_OUTPUT_PROPERTIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class Instructions implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USAGE = "Usage";
  private String usage;

  public static final String JSON_PROPERTY_SAMPLE_NOTEBOOK_URL = "SampleNotebookUrl";
  private String sampleNotebookUrl;

  public static final String JSON_PROPERTY_REPOSITORY_URL = "RepositoryUrl";
  private String repositoryUrl;

  public static final String JSON_PROPERTY_INPUT_PROPERTIES = "InputProperties";
  private InputProperties inputProperties;

  public static final String JSON_PROPERTY_OUTPUT_PROPERTIES = "OutputProperties";
  private OutputProperties outputProperties;

  public Instructions() {
  }

  public Instructions usage(String usage) {
    
    this.usage = usage;
    return this;
  }

  /**
   * Get usage
   * @return usage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsage() {
    return usage;
  }


  @JsonProperty(JSON_PROPERTY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsage(String usage) {
    this.usage = usage;
  }

  public Instructions sampleNotebookUrl(String sampleNotebookUrl) {
    
    this.sampleNotebookUrl = sampleNotebookUrl;
    return this;
  }

  /**
   * Get sampleNotebookUrl
   * @return sampleNotebookUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLE_NOTEBOOK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSampleNotebookUrl() {
    return sampleNotebookUrl;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLE_NOTEBOOK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleNotebookUrl(String sampleNotebookUrl) {
    this.sampleNotebookUrl = sampleNotebookUrl;
  }

  public Instructions repositoryUrl(String repositoryUrl) {
    
    this.repositoryUrl = repositoryUrl;
    return this;
  }

  /**
   * Get repositoryUrl
   * @return repositoryUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPOSITORY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRepositoryUrl() {
    return repositoryUrl;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepositoryUrl(String repositoryUrl) {
    this.repositoryUrl = repositoryUrl;
  }

  public Instructions inputProperties(InputProperties inputProperties) {
    
    this.inputProperties = inputProperties;
    return this;
  }

  /**
   * Get inputProperties
   * @return inputProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InputProperties getInputProperties() {
    return inputProperties;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputProperties(InputProperties inputProperties) {
    this.inputProperties = inputProperties;
  }

  public Instructions outputProperties(OutputProperties outputProperties) {
    
    this.outputProperties = outputProperties;
    return this;
  }

  /**
   * Get outputProperties
   * @return outputProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OutputProperties getOutputProperties() {
    return outputProperties;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputProperties(OutputProperties outputProperties) {
    this.outputProperties = outputProperties;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Instructions instructions = (Instructions) o;
    return Objects.equals(this.usage, instructions.usage) &&
        Objects.equals(this.sampleNotebookUrl, instructions.sampleNotebookUrl) &&
        Objects.equals(this.repositoryUrl, instructions.repositoryUrl) &&
        Objects.equals(this.inputProperties, instructions.inputProperties) &&
        Objects.equals(this.outputProperties, instructions.outputProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usage, sampleNotebookUrl, repositoryUrl, inputProperties, outputProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Instructions {\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    sampleNotebookUrl: ").append(toIndentedString(sampleNotebookUrl)).append("\n");
    sb.append("    repositoryUrl: ").append(toIndentedString(repositoryUrl)).append("\n");
    sb.append("    inputProperties: ").append(toIndentedString(inputProperties)).append("\n");
    sb.append("    outputProperties: ").append(toIndentedString(outputProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

