/*
 * MachineLearningProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.machinelearningproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SupportedInstanceTypes
 */
@JsonPropertyOrder({
  SupportedInstanceTypes.JSON_PROPERTY_BATCH_TRANSFORM,
  SupportedInstanceTypes.JSON_PROPERTY_REALTIME_INFERENCE,
  SupportedInstanceTypes.JSON_PROPERTY_TRAINING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class SupportedInstanceTypes implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BATCH_TRANSFORM = "BatchTransform";
  private List<String> batchTransform = new ArrayList<>();

  public static final String JSON_PROPERTY_REALTIME_INFERENCE = "RealtimeInference";
  private List<String> realtimeInference = new ArrayList<>();

  public static final String JSON_PROPERTY_TRAINING = "Training";
  private List<String> training = new ArrayList<>();

  public SupportedInstanceTypes() {
  }

  public SupportedInstanceTypes batchTransform(List<String> batchTransform) {
    
    this.batchTransform = batchTransform;
    return this;
  }

  public SupportedInstanceTypes addBatchTransformItem(String batchTransformItem) {
    if (this.batchTransform == null) {
      this.batchTransform = new ArrayList<>();
    }
    this.batchTransform.add(batchTransformItem);
    return this;
  }

  /**
   * Get batchTransform
   * @return batchTransform
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getBatchTransform() {
    return batchTransform;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_TRANSFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchTransform(List<String> batchTransform) {
    this.batchTransform = batchTransform;
  }

  public SupportedInstanceTypes realtimeInference(List<String> realtimeInference) {
    
    this.realtimeInference = realtimeInference;
    return this;
  }

  public SupportedInstanceTypes addRealtimeInferenceItem(String realtimeInferenceItem) {
    if (this.realtimeInference == null) {
      this.realtimeInference = new ArrayList<>();
    }
    this.realtimeInference.add(realtimeInferenceItem);
    return this;
  }

  /**
   * Get realtimeInference
   * @return realtimeInference
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRealtimeInference() {
    return realtimeInference;
  }


  @JsonProperty(JSON_PROPERTY_REALTIME_INFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRealtimeInference(List<String> realtimeInference) {
    this.realtimeInference = realtimeInference;
  }

  public SupportedInstanceTypes training(List<String> training) {
    
    this.training = training;
    return this;
  }

  public SupportedInstanceTypes addTrainingItem(String trainingItem) {
    if (this.training == null) {
      this.training = new ArrayList<>();
    }
    this.training.add(trainingItem);
    return this;
  }

  /**
   * Get training
   * @return training
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTraining() {
    return training;
  }


  @JsonProperty(JSON_PROPERTY_TRAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTraining(List<String> training) {
    this.training = training;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportedInstanceTypes supportedInstanceTypes = (SupportedInstanceTypes) o;
    return Objects.equals(this.batchTransform, supportedInstanceTypes.batchTransform) &&
        Objects.equals(this.realtimeInference, supportedInstanceTypes.realtimeInference) &&
        Objects.equals(this.training, supportedInstanceTypes.training);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchTransform, realtimeInference, training);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportedInstanceTypes {\n");
    sb.append("    batchTransform: ").append(toIndentedString(batchTransform)).append("\n");
    sb.append("    realtimeInference: ").append(toIndentedString(realtimeInference)).append("\n");
    sb.append("    training: ").append(toIndentedString(training)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

