/*
 * Offer_1_0
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.offer_1_0;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateReplacementOfferUsingResaleAuthorizationChangeDetail
 */
@JsonPropertyOrder({
  CreateReplacementOfferUsingResaleAuthorizationChangeDetail.JSON_PROPERTY_RESALE_AUTHORIZATION_ID,
  CreateReplacementOfferUsingResaleAuthorizationChangeDetail.JSON_PROPERTY_AGREEMENT_ID,
  CreateReplacementOfferUsingResaleAuthorizationChangeDetail.JSON_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateReplacementOfferUsingResaleAuthorizationChangeDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_RESALE_AUTHORIZATION_ID = "ResaleAuthorizationId";
  private String resaleAuthorizationId;

  public static final String JSON_PROPERTY_AGREEMENT_ID = "AgreementId";
  private String agreementId;

  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public CreateReplacementOfferUsingResaleAuthorizationChangeDetail() {
  }

  public CreateReplacementOfferUsingResaleAuthorizationChangeDetail resaleAuthorizationId(String resaleAuthorizationId) {
    
    this.resaleAuthorizationId = resaleAuthorizationId;
    return this;
  }

   /**
   * Get resaleAuthorizationId
   * @return resaleAuthorizationId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESALE_AUTHORIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResaleAuthorizationId() {
    return resaleAuthorizationId;
  }


  @JsonProperty(JSON_PROPERTY_RESALE_AUTHORIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResaleAuthorizationId(String resaleAuthorizationId) {
    this.resaleAuthorizationId = resaleAuthorizationId;
  }


  public CreateReplacementOfferUsingResaleAuthorizationChangeDetail agreementId(String agreementId) {
    
    this.agreementId = agreementId;
    return this;
  }

   /**
   * Get agreementId
   * @return agreementId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgreementId() {
    return agreementId;
  }


  @JsonProperty(JSON_PROPERTY_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgreementId(String agreementId) {
    this.agreementId = agreementId;
  }


  public CreateReplacementOfferUsingResaleAuthorizationChangeDetail name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReplacementOfferUsingResaleAuthorizationChangeDetail createReplacementOfferUsingResaleAuthorizationChangeDetail = (CreateReplacementOfferUsingResaleAuthorizationChangeDetail) o;
    return Objects.equals(this.resaleAuthorizationId, createReplacementOfferUsingResaleAuthorizationChangeDetail.resaleAuthorizationId) &&
        Objects.equals(this.agreementId, createReplacementOfferUsingResaleAuthorizationChangeDetail.agreementId) &&
        Objects.equals(this.name, createReplacementOfferUsingResaleAuthorizationChangeDetail.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resaleAuthorizationId, agreementId, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReplacementOfferUsingResaleAuthorizationChangeDetail {\n");
    sb.append("    resaleAuthorizationId: ").append(toIndentedString(resaleAuthorizationId)).append("\n");
    sb.append("    agreementId: ").append(toIndentedString(agreementId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

