/*
 * SaaSProduct_1_0
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.Description;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.Dimension;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.EntityTargeting;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.PromotionalResources;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.SupportInformation;
import com.amazonaws.services.marketplacecatalog.model.saasproduct_1_0.Version;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SaaSProductEntityDetail
 */
@JsonPropertyOrder({
  SaaSProductEntityDetail.JSON_PROPERTY_DESCRIPTION,
  SaaSProductEntityDetail.JSON_PROPERTY_PROMOTIONAL_RESOURCES,
  SaaSProductEntityDetail.JSON_PROPERTY_SUPPORT_INFORMATION,
  SaaSProductEntityDetail.JSON_PROPERTY_DIMENSIONS,
  SaaSProductEntityDetail.JSON_PROPERTY_VERSIONS,
  SaaSProductEntityDetail.JSON_PROPERTY_TARGETING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SaaSProductEntityDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private Description description;

  public static final String JSON_PROPERTY_PROMOTIONAL_RESOURCES = "PromotionalResources";
  private PromotionalResources promotionalResources;

  public static final String JSON_PROPERTY_SUPPORT_INFORMATION = "SupportInformation";
  private SupportInformation supportInformation;

  public static final String JSON_PROPERTY_DIMENSIONS = "Dimensions";
  private List<Dimension> dimensions;

  public static final String JSON_PROPERTY_VERSIONS = "Versions";
  private List<Version> versions;

  public static final String JSON_PROPERTY_TARGETING = "Targeting";
  private EntityTargeting targeting;

  public SaaSProductEntityDetail() {
  }

  public SaaSProductEntityDetail description(Description description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Description getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(Description description) {
    this.description = description;
  }


  public SaaSProductEntityDetail promotionalResources(PromotionalResources promotionalResources) {
    
    this.promotionalResources = promotionalResources;
    return this;
  }

   /**
   * Get promotionalResources
   * @return promotionalResources
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMOTIONAL_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PromotionalResources getPromotionalResources() {
    return promotionalResources;
  }


  @JsonProperty(JSON_PROPERTY_PROMOTIONAL_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromotionalResources(PromotionalResources promotionalResources) {
    this.promotionalResources = promotionalResources;
  }


  public SaaSProductEntityDetail supportInformation(SupportInformation supportInformation) {
    
    this.supportInformation = supportInformation;
    return this;
  }

   /**
   * Get supportInformation
   * @return supportInformation
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SupportInformation getSupportInformation() {
    return supportInformation;
  }


  @JsonProperty(JSON_PROPERTY_SUPPORT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupportInformation(SupportInformation supportInformation) {
    this.supportInformation = supportInformation;
  }


  public SaaSProductEntityDetail dimensions(List<Dimension> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public SaaSProductEntityDetail addDimensionsItem(Dimension dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Dimension> getDimensions() {
    return dimensions;
  }


  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimensions(List<Dimension> dimensions) {
    this.dimensions = dimensions;
  }


  public SaaSProductEntityDetail versions(List<Version> versions) {
    
    this.versions = versions;
    return this;
  }

  public SaaSProductEntityDetail addVersionsItem(Version versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Get versions
   * @return versions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Version> getVersions() {
    return versions;
  }


  @JsonProperty(JSON_PROPERTY_VERSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersions(List<Version> versions) {
    this.versions = versions;
  }


  public SaaSProductEntityDetail targeting(EntityTargeting targeting) {
    
    this.targeting = targeting;
    return this;
  }

   /**
   * Get targeting
   * @return targeting
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGETING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntityTargeting getTargeting() {
    return targeting;
  }


  @JsonProperty(JSON_PROPERTY_TARGETING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargeting(EntityTargeting targeting) {
    this.targeting = targeting;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaaSProductEntityDetail saaSProductEntityDetail = (SaaSProductEntityDetail) o;
    return Objects.equals(this.description, saaSProductEntityDetail.description) &&
        Objects.equals(this.promotionalResources, saaSProductEntityDetail.promotionalResources) &&
        Objects.equals(this.supportInformation, saaSProductEntityDetail.supportInformation) &&
        Objects.equals(this.dimensions, saaSProductEntityDetail.dimensions) &&
        Objects.equals(this.versions, saaSProductEntityDetail.versions) &&
        Objects.equals(this.targeting, saaSProductEntityDetail.targeting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, promotionalResources, supportInformation, dimensions, versions, targeting);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaaSProductEntityDetail {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    promotionalResources: ").append(toIndentedString(promotionalResources)).append("\n");
    sb.append("    supportInformation: ").append(toIndentedString(supportInformation)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("    targeting: ").append(toIndentedString(targeting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

