/*
 * ResaleAuthorization_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.resaleauthorization_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.resaleauthorization_1_0.entitytype.BuyerAccount;
import com.amazonaws.services.marketplacecatalog.model.resaleauthorization_1_0.entitytype.PartnerAccount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PositiveTargeting
 */
@JsonPropertyOrder({
  PositiveTargeting.JSON_PROPERTY_BUYER_ACCOUNTS,
  PositiveTargeting.JSON_PROPERTY_PARTNER_ACCOUNTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class PositiveTargeting implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BUYER_ACCOUNTS = "BuyerAccounts";
  private List<BuyerAccount> buyerAccounts = new ArrayList<>();

  public static final String JSON_PROPERTY_PARTNER_ACCOUNTS = "PartnerAccounts";
  private List<PartnerAccount> partnerAccounts = new ArrayList<>();

  public PositiveTargeting() {
  }

  public PositiveTargeting buyerAccounts(List<BuyerAccount> buyerAccounts) {
    
    this.buyerAccounts = buyerAccounts;
    return this;
  }

  public PositiveTargeting addBuyerAccountsItem(BuyerAccount buyerAccountsItem) {
    if (this.buyerAccounts == null) {
      this.buyerAccounts = new ArrayList<>();
    }
    this.buyerAccounts.add(buyerAccountsItem);
    return this;
  }

  /**
   * Get buyerAccounts
   * @return buyerAccounts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUYER_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BuyerAccount> getBuyerAccounts() {
    return buyerAccounts;
  }


  @JsonProperty(JSON_PROPERTY_BUYER_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyerAccounts(List<BuyerAccount> buyerAccounts) {
    this.buyerAccounts = buyerAccounts;
  }

  public PositiveTargeting partnerAccounts(List<PartnerAccount> partnerAccounts) {
    
    this.partnerAccounts = partnerAccounts;
    return this;
  }

  public PositiveTargeting addPartnerAccountsItem(PartnerAccount partnerAccountsItem) {
    if (this.partnerAccounts == null) {
      this.partnerAccounts = new ArrayList<>();
    }
    this.partnerAccounts.add(partnerAccountsItem);
    return this;
  }

  /**
   * Get partnerAccounts
   * @return partnerAccounts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTNER_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PartnerAccount> getPartnerAccounts() {
    return partnerAccounts;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartnerAccounts(List<PartnerAccount> partnerAccounts) {
    this.partnerAccounts = partnerAccounts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PositiveTargeting positiveTargeting = (PositiveTargeting) o;
    return Objects.equals(this.buyerAccounts, positiveTargeting.buyerAccounts) &&
        Objects.equals(this.partnerAccounts, positiveTargeting.partnerAccounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyerAccounts, partnerAccounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PositiveTargeting {\n");
    sb.append("    buyerAccounts: ").append(toIndentedString(buyerAccounts)).append("\n");
    sb.append("    partnerAccounts: ").append(toIndentedString(partnerAccounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

