/*
 * Offer_1_0_Appendix
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.offer_1_0.appendix;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NegativeTargeting
 */
@JsonPropertyOrder({
  NegativeTargeting.JSON_PROPERTY_COUNTRY_CODES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NegativeTargeting implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COUNTRY_CODES = "CountryCodes";
  private List<String> countryCodes = new ArrayList<>();

  public NegativeTargeting() {
  }

  public NegativeTargeting countryCodes(List<String> countryCodes) {
    
    this.countryCodes = countryCodes;
    return this;
  }

  public NegativeTargeting addCountryCodesItem(String countryCodesItem) {
    if (this.countryCodes == null) {
      this.countryCodes = new ArrayList<>();
    }
    this.countryCodes.add(countryCodesItem);
    return this;
  }

   /**
   * Get countryCodes
   * @return countryCodes
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getCountryCodes() {
    return countryCodes;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryCodes(List<String> countryCodes) {
    this.countryCodes = countryCodes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NegativeTargeting negativeTargeting = (NegativeTargeting) o;
    return Objects.equals(this.countryCodes, negativeTargeting.countryCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NegativeTargeting {\n");
    sb.append("    countryCodes: ").append(toIndentedString(countryCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

