/*
 * Offer_1_0_Appendix
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.offer_1_0.appendix;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.offer_1_0.appendix.BillingPeriod;
import com.amazonaws.services.marketplacecatalog.model.offer_1_0.appendix.CurrencyCode;
import com.amazonaws.services.marketplacecatalog.model.offer_1_0.appendix.RecurringPaymentTermType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RecurringPaymentTerm
 */
@JsonPropertyOrder({
  RecurringPaymentTerm.JSON_PROPERTY_TYPE,
  RecurringPaymentTerm.JSON_PROPERTY_CURRENCY_CODE,
  RecurringPaymentTerm.JSON_PROPERTY_BILLING_PERIOD,
  RecurringPaymentTerm.JSON_PROPERTY_PRICE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RecurringPaymentTerm implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TYPE = "Type";
  private RecurringPaymentTermType type;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "CurrencyCode";
  private CurrencyCode currencyCode;

  public static final String JSON_PROPERTY_BILLING_PERIOD = "BillingPeriod";
  private BillingPeriod billingPeriod;

  public static final String JSON_PROPERTY_PRICE = "Price";
  private String price;

  public RecurringPaymentTerm() {
  }

  public RecurringPaymentTerm type(RecurringPaymentTermType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RecurringPaymentTermType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(RecurringPaymentTermType type) {
    this.type = type;
  }


  public RecurringPaymentTerm currencyCode(CurrencyCode currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CurrencyCode getCurrencyCode() {
    return currencyCode;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrencyCode(CurrencyCode currencyCode) {
    this.currencyCode = currencyCode;
  }


  public RecurringPaymentTerm billingPeriod(BillingPeriod billingPeriod) {
    
    this.billingPeriod = billingPeriod;
    return this;
  }

   /**
   * Get billingPeriod
   * @return billingPeriod
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BILLING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BillingPeriod getBillingPeriod() {
    return billingPeriod;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBillingPeriod(BillingPeriod billingPeriod) {
    this.billingPeriod = billingPeriod;
  }


  public RecurringPaymentTerm price(String price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(String price) {
    this.price = price;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecurringPaymentTerm recurringPaymentTerm = (RecurringPaymentTerm) o;
    return Objects.equals(this.type, recurringPaymentTerm.type) &&
        Objects.equals(this.currencyCode, recurringPaymentTerm.currencyCode) &&
        Objects.equals(this.billingPeriod, recurringPaymentTerm.billingPeriod) &&
        Objects.equals(this.price, recurringPaymentTerm.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, currencyCode, billingPeriod, price);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecurringPaymentTerm {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    billingPeriod: ").append(toIndentedString(billingPeriod)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

