/*
 * Offer_1_0_Appendix
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.offer_1_0.appendix;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ScheduleItem
 */
@JsonPropertyOrder({
  ScheduleItem.JSON_PROPERTY_CHARGE_DATE,
  ScheduleItem.JSON_PROPERTY_CHARGE_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ScheduleItem implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CHARGE_DATE = "ChargeDate";
  private String chargeDate;

  public static final String JSON_PROPERTY_CHARGE_AMOUNT = "ChargeAmount";
  private String chargeAmount;

  public ScheduleItem() {
  }

  public ScheduleItem chargeDate(String chargeDate) {
    
    this.chargeDate = chargeDate;
    return this;
  }

   /**
   * Get chargeDate
   * @return chargeDate
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHARGE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChargeDate() {
    return chargeDate;
  }


  @JsonProperty(JSON_PROPERTY_CHARGE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChargeDate(String chargeDate) {
    this.chargeDate = chargeDate;
  }


  public ScheduleItem chargeAmount(String chargeAmount) {
    
    this.chargeAmount = chargeAmount;
    return this;
  }

   /**
   * Get chargeAmount
   * @return chargeAmount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHARGE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChargeAmount() {
    return chargeAmount;
  }


  @JsonProperty(JSON_PROPERTY_CHARGE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChargeAmount(String chargeAmount) {
    this.chargeAmount = chargeAmount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleItem scheduleItem = (ScheduleItem) o;
    return Objects.equals(this.chargeDate, scheduleItem.chargeDate) &&
        Objects.equals(this.chargeAmount, scheduleItem.chargeAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeDate, chargeAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleItem {\n");
    sb.append("    chargeDate: ").append(toIndentedString(chargeDate)).append("\n");
    sb.append("    chargeAmount: ").append(toIndentedString(chargeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

