/*
 * ProcurementPolicy_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.procurementpolicy_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.procurementpolicy_1_0.entitytype.ModelConfiguration;
import com.amazonaws.services.marketplacecatalog.model.procurementpolicy_1_0.entitytype.Statement;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProcurementPolicyEntityDetail
 */
@JsonPropertyOrder({
  ProcurementPolicyEntityDetail.JSON_PROPERTY_NAME,
  ProcurementPolicyEntityDetail.JSON_PROPERTY_DESCRIPTION,
  ProcurementPolicyEntityDetail.JSON_PROPERTY_STATEMENTS,
  ProcurementPolicyEntityDetail.JSON_PROPERTY_CONFIGURATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProcurementPolicyEntityDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private String description;

  public static final String JSON_PROPERTY_STATEMENTS = "Statements";
  private List<Statement> statements;

  public static final String JSON_PROPERTY_CONFIGURATION = "Configuration";
  private ModelConfiguration _configuration;

  public ProcurementPolicyEntityDetail() {
  }

  public ProcurementPolicyEntityDetail name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ProcurementPolicyEntityDetail description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ProcurementPolicyEntityDetail statements(List<Statement> statements) {
    
    this.statements = statements;
    return this;
  }

  public ProcurementPolicyEntityDetail addStatementsItem(Statement statementsItem) {
    if (this.statements == null) {
      this.statements = new ArrayList<>();
    }
    this.statements.add(statementsItem);
    return this;
  }

   /**
   * Get statements
   * @return statements
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Statement> getStatements() {
    return statements;
  }


  @JsonProperty(JSON_PROPERTY_STATEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatements(List<Statement> statements) {
    this.statements = statements;
  }


  public ProcurementPolicyEntityDetail _configuration(ModelConfiguration _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModelConfiguration getConfiguration() {
    return _configuration;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfiguration(ModelConfiguration _configuration) {
    this._configuration = _configuration;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcurementPolicyEntityDetail procurementPolicyEntityDetail = (ProcurementPolicyEntityDetail) o;
    return Objects.equals(this.name, procurementPolicyEntityDetail.name) &&
        Objects.equals(this.description, procurementPolicyEntityDetail.description) &&
        Objects.equals(this.statements, procurementPolicyEntityDetail.statements) &&
        Objects.equals(this._configuration, procurementPolicyEntityDetail._configuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, statements, _configuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcurementPolicyEntityDetail {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    statements: ").append(toIndentedString(statements)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

