/*
 * Experience_1_0
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.experience_1_0;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BrandingConfiguration
 */
@JsonPropertyOrder({
  BrandingConfiguration.JSON_PROPERTY_TITLE,
  BrandingConfiguration.JSON_PROPERTY_INFORMATION,
  BrandingConfiguration.JSON_PROPERTY_THEME_COLOR,
  BrandingConfiguration.JSON_PROPERTY_LOGO_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BrandingConfiguration implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TITLE = "Title";
  private String title;

  public static final String JSON_PROPERTY_INFORMATION = "Information";
  private String information;

  public static final String JSON_PROPERTY_THEME_COLOR = "ThemeColor";
  private String themeColor;

  public static final String JSON_PROPERTY_LOGO_URL = "LogoUrl";
  private String logoUrl;

  public BrandingConfiguration() {
  }

  public BrandingConfiguration title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public BrandingConfiguration information(String information) {
    
    this.information = information;
    return this;
  }

   /**
   * Get information
   * @return information
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInformation() {
    return information;
  }


  @JsonProperty(JSON_PROPERTY_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInformation(String information) {
    this.information = information;
  }


  public BrandingConfiguration themeColor(String themeColor) {
    
    this.themeColor = themeColor;
    return this;
  }

   /**
   * Get themeColor
   * @return themeColor
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THEME_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getThemeColor() {
    return themeColor;
  }


  @JsonProperty(JSON_PROPERTY_THEME_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThemeColor(String themeColor) {
    this.themeColor = themeColor;
  }


  public BrandingConfiguration logoUrl(String logoUrl) {
    
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoUrl() {
    return logoUrl;
  }


  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandingConfiguration brandingConfiguration = (BrandingConfiguration) o;
    return Objects.equals(this.title, brandingConfiguration.title) &&
        Objects.equals(this.information, brandingConfiguration.information) &&
        Objects.equals(this.themeColor, brandingConfiguration.themeColor) &&
        Objects.equals(this.logoUrl, brandingConfiguration.logoUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, information, themeColor, logoUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandingConfiguration {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    information: ").append(toIndentedString(information)).append("\n");
    sb.append("    themeColor: ").append(toIndentedString(themeColor)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

