/*
 * ContainerProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype.DeliveryOptionCompatibility;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype.EnvironmentOverrideParameter;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype.Instructions;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype.OverrideParameter;
import com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype.Recommendations;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeliveryOption
 */
@JsonPropertyOrder({
  DeliveryOption.JSON_PROPERTY_ID,
  DeliveryOption.JSON_PROPERTY_TYPE,
  DeliveryOption.JSON_PROPERTY_SOURCE_ID,
  DeliveryOption.JSON_PROPERTY_TITLE,
  DeliveryOption.JSON_PROPERTY_SHORT_DESCRIPTION,
  DeliveryOption.JSON_PROPERTY_IS_RECOMMENDED,
  DeliveryOption.JSON_PROPERTY_COMPATIBILITY,
  DeliveryOption.JSON_PROPERTY_INSTRUCTIONS,
  DeliveryOption.JSON_PROPERTY_RECOMMENDATIONS,
  DeliveryOption.JSON_PROPERTY_VISIBILITY,
  DeliveryOption.JSON_PROPERTY_QUICK_LAUNCH_ENABLED,
  DeliveryOption.JSON_PROPERTY_RELEASE_NAME,
  DeliveryOption.JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME,
  DeliveryOption.JSON_PROPERTY_NAMESPACE,
  DeliveryOption.JSON_PROPERTY_OVERRIDE_PARAMETERS,
  DeliveryOption.JSON_PROPERTY_ADD_ON_TYPE,
  DeliveryOption.JSON_PROPERTY_ENVIRONMENT_OVERRIDE_PARAMETERS,
  DeliveryOption.JSON_PROPERTY_DISPLAY_ADD_ON_NAME,
  DeliveryOption.JSON_PROPERTY_ADD_ON_NAME,
  DeliveryOption.JSON_PROPERTY_DISPLAY_ADD_ON_VERSION,
  DeliveryOption.JSON_PROPERTY_ADD_ON_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeliveryOption implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "Id";
  private String id;

  public static final String JSON_PROPERTY_TYPE = "Type";
  private String type;

  public static final String JSON_PROPERTY_SOURCE_ID = "SourceId";
  private String sourceId;

  public static final String JSON_PROPERTY_TITLE = "Title";
  private String title;

  public static final String JSON_PROPERTY_SHORT_DESCRIPTION = "ShortDescription";
  private String shortDescription;

  public static final String JSON_PROPERTY_IS_RECOMMENDED = "isRecommended";
  private Boolean isRecommended;

  public static final String JSON_PROPERTY_COMPATIBILITY = "Compatibility";
  private DeliveryOptionCompatibility compatibility;

  public static final String JSON_PROPERTY_INSTRUCTIONS = "Instructions";
  private Instructions instructions;

  public static final String JSON_PROPERTY_RECOMMENDATIONS = "Recommendations";
  private Recommendations recommendations;

  public static final String JSON_PROPERTY_VISIBILITY = "Visibility";
  private String visibility;

  public static final String JSON_PROPERTY_QUICK_LAUNCH_ENABLED = "QuickLaunchEnabled";
  private Boolean quickLaunchEnabled;

  public static final String JSON_PROPERTY_RELEASE_NAME = "ReleaseName";
  private String releaseName;

  public static final String JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME = "MarketplaceServiceAccountName";
  private String marketplaceServiceAccountName;

  public static final String JSON_PROPERTY_NAMESPACE = "Namespace";
  private String namespace;

  public static final String JSON_PROPERTY_OVERRIDE_PARAMETERS = "OverrideParameters";
  private List<OverrideParameter> overrideParameters;

  public static final String JSON_PROPERTY_ADD_ON_TYPE = "AddOnType";
  private String addOnType;

  public static final String JSON_PROPERTY_ENVIRONMENT_OVERRIDE_PARAMETERS = "EnvironmentOverrideParameters";
  private List<EnvironmentOverrideParameter> environmentOverrideParameters;

  public static final String JSON_PROPERTY_DISPLAY_ADD_ON_NAME = "DisplayAddOnName";
  private String displayAddOnName;

  public static final String JSON_PROPERTY_ADD_ON_NAME = "AddOnName";
  private String addOnName;

  public static final String JSON_PROPERTY_DISPLAY_ADD_ON_VERSION = "DisplayAddOnVersion";
  private String displayAddOnVersion;

  public static final String JSON_PROPERTY_ADD_ON_VERSION = "AddOnVersion";
  private String addOnVersion;

  public DeliveryOption() {
  }

  public DeliveryOption id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public DeliveryOption type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public DeliveryOption sourceId(String sourceId) {
    
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  public DeliveryOption title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public DeliveryOption shortDescription(String shortDescription) {
    
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * Get shortDescription
   * @return shortDescription
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShortDescription() {
    return shortDescription;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }


  public DeliveryOption isRecommended(Boolean isRecommended) {
    
    this.isRecommended = isRecommended;
    return this;
  }

   /**
   * Get isRecommended
   * @return isRecommended
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_RECOMMENDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsRecommended() {
    return isRecommended;
  }


  @JsonProperty(JSON_PROPERTY_IS_RECOMMENDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsRecommended(Boolean isRecommended) {
    this.isRecommended = isRecommended;
  }


  public DeliveryOption compatibility(DeliveryOptionCompatibility compatibility) {
    
    this.compatibility = compatibility;
    return this;
  }

   /**
   * Get compatibility
   * @return compatibility
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPATIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryOptionCompatibility getCompatibility() {
    return compatibility;
  }


  @JsonProperty(JSON_PROPERTY_COMPATIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompatibility(DeliveryOptionCompatibility compatibility) {
    this.compatibility = compatibility;
  }


  public DeliveryOption instructions(Instructions instructions) {
    
    this.instructions = instructions;
    return this;
  }

   /**
   * Get instructions
   * @return instructions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Instructions getInstructions() {
    return instructions;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstructions(Instructions instructions) {
    this.instructions = instructions;
  }


  public DeliveryOption recommendations(Recommendations recommendations) {
    
    this.recommendations = recommendations;
    return this;
  }

   /**
   * Get recommendations
   * @return recommendations
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECOMMENDATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Recommendations getRecommendations() {
    return recommendations;
  }


  @JsonProperty(JSON_PROPERTY_RECOMMENDATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecommendations(Recommendations recommendations) {
    this.recommendations = recommendations;
  }


  public DeliveryOption visibility(String visibility) {
    
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibility() {
    return visibility;
  }


  @JsonProperty(JSON_PROPERTY_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibility(String visibility) {
    this.visibility = visibility;
  }


  public DeliveryOption quickLaunchEnabled(Boolean quickLaunchEnabled) {
    
    this.quickLaunchEnabled = quickLaunchEnabled;
    return this;
  }

   /**
   * Get quickLaunchEnabled
   * @return quickLaunchEnabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getQuickLaunchEnabled() {
    return quickLaunchEnabled;
  }


  @JsonProperty(JSON_PROPERTY_QUICK_LAUNCH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuickLaunchEnabled(Boolean quickLaunchEnabled) {
    this.quickLaunchEnabled = quickLaunchEnabled;
  }


  public DeliveryOption releaseName(String releaseName) {
    
    this.releaseName = releaseName;
    return this;
  }

   /**
   * Get releaseName
   * @return releaseName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELEASE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReleaseName() {
    return releaseName;
  }


  @JsonProperty(JSON_PROPERTY_RELEASE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReleaseName(String releaseName) {
    this.releaseName = releaseName;
  }


  public DeliveryOption marketplaceServiceAccountName(String marketplaceServiceAccountName) {
    
    this.marketplaceServiceAccountName = marketplaceServiceAccountName;
    return this;
  }

   /**
   * Get marketplaceServiceAccountName
   * @return marketplaceServiceAccountName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMarketplaceServiceAccountName() {
    return marketplaceServiceAccountName;
  }


  @JsonProperty(JSON_PROPERTY_MARKETPLACE_SERVICE_ACCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketplaceServiceAccountName(String marketplaceServiceAccountName) {
    this.marketplaceServiceAccountName = marketplaceServiceAccountName;
  }


  public DeliveryOption namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public DeliveryOption overrideParameters(List<OverrideParameter> overrideParameters) {
    
    this.overrideParameters = overrideParameters;
    return this;
  }

  public DeliveryOption addOverrideParametersItem(OverrideParameter overrideParametersItem) {
    if (this.overrideParameters == null) {
      this.overrideParameters = new ArrayList<>();
    }
    this.overrideParameters.add(overrideParametersItem);
    return this;
  }

   /**
   * Get overrideParameters
   * @return overrideParameters
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OverrideParameter> getOverrideParameters() {
    return overrideParameters;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideParameters(List<OverrideParameter> overrideParameters) {
    this.overrideParameters = overrideParameters;
  }


  public DeliveryOption addOnType(String addOnType) {
    
    this.addOnType = addOnType;
    return this;
  }

   /**
   * Get addOnType
   * @return addOnType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADD_ON_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddOnType() {
    return addOnType;
  }


  @JsonProperty(JSON_PROPERTY_ADD_ON_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddOnType(String addOnType) {
    this.addOnType = addOnType;
  }


  public DeliveryOption environmentOverrideParameters(List<EnvironmentOverrideParameter> environmentOverrideParameters) {
    
    this.environmentOverrideParameters = environmentOverrideParameters;
    return this;
  }

  public DeliveryOption addEnvironmentOverrideParametersItem(EnvironmentOverrideParameter environmentOverrideParametersItem) {
    if (this.environmentOverrideParameters == null) {
      this.environmentOverrideParameters = new ArrayList<>();
    }
    this.environmentOverrideParameters.add(environmentOverrideParametersItem);
    return this;
  }

   /**
   * Get environmentOverrideParameters
   * @return environmentOverrideParameters
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENVIRONMENT_OVERRIDE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EnvironmentOverrideParameter> getEnvironmentOverrideParameters() {
    return environmentOverrideParameters;
  }


  @JsonProperty(JSON_PROPERTY_ENVIRONMENT_OVERRIDE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvironmentOverrideParameters(List<EnvironmentOverrideParameter> environmentOverrideParameters) {
    this.environmentOverrideParameters = environmentOverrideParameters;
  }


  public DeliveryOption displayAddOnName(String displayAddOnName) {
    
    this.displayAddOnName = displayAddOnName;
    return this;
  }

   /**
   * Get displayAddOnName
   * @return displayAddOnName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_ADD_ON_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayAddOnName() {
    return displayAddOnName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_ADD_ON_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayAddOnName(String displayAddOnName) {
    this.displayAddOnName = displayAddOnName;
  }


  public DeliveryOption addOnName(String addOnName) {
    
    this.addOnName = addOnName;
    return this;
  }

   /**
   * Get addOnName
   * @return addOnName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADD_ON_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddOnName() {
    return addOnName;
  }


  @JsonProperty(JSON_PROPERTY_ADD_ON_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddOnName(String addOnName) {
    this.addOnName = addOnName;
  }


  public DeliveryOption displayAddOnVersion(String displayAddOnVersion) {
    
    this.displayAddOnVersion = displayAddOnVersion;
    return this;
  }

   /**
   * Get displayAddOnVersion
   * @return displayAddOnVersion
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_ADD_ON_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayAddOnVersion() {
    return displayAddOnVersion;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_ADD_ON_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayAddOnVersion(String displayAddOnVersion) {
    this.displayAddOnVersion = displayAddOnVersion;
  }


  public DeliveryOption addOnVersion(String addOnVersion) {
    
    this.addOnVersion = addOnVersion;
    return this;
  }

   /**
   * Get addOnVersion
   * @return addOnVersion
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADD_ON_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddOnVersion() {
    return addOnVersion;
  }


  @JsonProperty(JSON_PROPERTY_ADD_ON_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddOnVersion(String addOnVersion) {
    this.addOnVersion = addOnVersion;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryOption deliveryOption = (DeliveryOption) o;
    return Objects.equals(this.id, deliveryOption.id) &&
        Objects.equals(this.type, deliveryOption.type) &&
        Objects.equals(this.sourceId, deliveryOption.sourceId) &&
        Objects.equals(this.title, deliveryOption.title) &&
        Objects.equals(this.shortDescription, deliveryOption.shortDescription) &&
        Objects.equals(this.isRecommended, deliveryOption.isRecommended) &&
        Objects.equals(this.compatibility, deliveryOption.compatibility) &&
        Objects.equals(this.instructions, deliveryOption.instructions) &&
        Objects.equals(this.recommendations, deliveryOption.recommendations) &&
        Objects.equals(this.visibility, deliveryOption.visibility) &&
        Objects.equals(this.quickLaunchEnabled, deliveryOption.quickLaunchEnabled) &&
        Objects.equals(this.releaseName, deliveryOption.releaseName) &&
        Objects.equals(this.marketplaceServiceAccountName, deliveryOption.marketplaceServiceAccountName) &&
        Objects.equals(this.namespace, deliveryOption.namespace) &&
        Objects.equals(this.overrideParameters, deliveryOption.overrideParameters) &&
        Objects.equals(this.addOnType, deliveryOption.addOnType) &&
        Objects.equals(this.environmentOverrideParameters, deliveryOption.environmentOverrideParameters) &&
        Objects.equals(this.displayAddOnName, deliveryOption.displayAddOnName) &&
        Objects.equals(this.addOnName, deliveryOption.addOnName) &&
        Objects.equals(this.displayAddOnVersion, deliveryOption.displayAddOnVersion) &&
        Objects.equals(this.addOnVersion, deliveryOption.addOnVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, sourceId, title, shortDescription, isRecommended, compatibility, instructions, recommendations, visibility, quickLaunchEnabled, releaseName, marketplaceServiceAccountName, namespace, overrideParameters, addOnType, environmentOverrideParameters, displayAddOnName, addOnName, displayAddOnVersion, addOnVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryOption {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    isRecommended: ").append(toIndentedString(isRecommended)).append("\n");
    sb.append("    compatibility: ").append(toIndentedString(compatibility)).append("\n");
    sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
    sb.append("    recommendations: ").append(toIndentedString(recommendations)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    quickLaunchEnabled: ").append(toIndentedString(quickLaunchEnabled)).append("\n");
    sb.append("    releaseName: ").append(toIndentedString(releaseName)).append("\n");
    sb.append("    marketplaceServiceAccountName: ").append(toIndentedString(marketplaceServiceAccountName)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    overrideParameters: ").append(toIndentedString(overrideParameters)).append("\n");
    sb.append("    addOnType: ").append(toIndentedString(addOnType)).append("\n");
    sb.append("    environmentOverrideParameters: ").append(toIndentedString(environmentOverrideParameters)).append("\n");
    sb.append("    displayAddOnName: ").append(toIndentedString(displayAddOnName)).append("\n");
    sb.append("    addOnName: ").append(toIndentedString(addOnName)).append("\n");
    sb.append("    displayAddOnVersion: ").append(toIndentedString(displayAddOnVersion)).append("\n");
    sb.append("    addOnVersion: ").append(toIndentedString(addOnVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

