/*
 * ContainerProduct_1_0_EntityType
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.containerproduct_1_0.entitytype;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignatureVerificationKey
 */
@JsonPropertyOrder({
  SignatureVerificationKey.JSON_PROPERTY_PUBLIC_KEY,
  SignatureVerificationKey.JSON_PROPERTY_STATUS,
  SignatureVerificationKey.JSON_PROPERTY_PUBLIC_KEY_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SignatureVerificationKey implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PUBLIC_KEY = "PublicKey";
  private String publicKey;

  public static final String JSON_PROPERTY_STATUS = "Status";
  private String status;

  public static final String JSON_PROPERTY_PUBLIC_KEY_VERSION = "PublicKeyVersion";
  private Integer publicKeyVersion;

  public SignatureVerificationKey() {
  }

  public SignatureVerificationKey publicKey(String publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Get publicKey
   * @return publicKey
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublicKey() {
    return publicKey;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }


  public SignatureVerificationKey status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public SignatureVerificationKey publicKeyVersion(Integer publicKeyVersion) {
    
    this.publicKeyVersion = publicKeyVersion;
    return this;
  }

   /**
   * Get publicKeyVersion
   * @return publicKeyVersion
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPublicKeyVersion() {
    return publicKeyVersion;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicKeyVersion(Integer publicKeyVersion) {
    this.publicKeyVersion = publicKeyVersion;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureVerificationKey signatureVerificationKey = (SignatureVerificationKey) o;
    return Objects.equals(this.publicKey, signatureVerificationKey.publicKey) &&
        Objects.equals(this.status, signatureVerificationKey.status) &&
        Objects.equals(this.publicKeyVersion, signatureVerificationKey.publicKeyVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicKey, status, publicKeyVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureVerificationKey {\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    publicKeyVersion: ").append(toIndentedString(publicKeyVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

