/*
 * ResaleAuthorization_1_0
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.resaleauthorization_1_0;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateResaleAuthorizationChangeDetail
 */
@JsonPropertyOrder({
  CreateResaleAuthorizationChangeDetail.JSON_PROPERTY_NAME,
  CreateResaleAuthorizationChangeDetail.JSON_PROPERTY_DESCRIPTION,
  CreateResaleAuthorizationChangeDetail.JSON_PROPERTY_PRODUCT_ID,
  CreateResaleAuthorizationChangeDetail.JSON_PROPERTY_RESELLER_ACCOUNT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateResaleAuthorizationChangeDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private String description;

  public static final String JSON_PROPERTY_PRODUCT_ID = "ProductId";
  private String productId;

  public static final String JSON_PROPERTY_RESELLER_ACCOUNT_ID = "ResellerAccountId";
  private String resellerAccountId;

  public CreateResaleAuthorizationChangeDetail() {
  }

  public CreateResaleAuthorizationChangeDetail name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public CreateResaleAuthorizationChangeDetail description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public CreateResaleAuthorizationChangeDetail productId(String productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(String productId) {
    this.productId = productId;
  }


  public CreateResaleAuthorizationChangeDetail resellerAccountId(String resellerAccountId) {
    
    this.resellerAccountId = resellerAccountId;
    return this;
  }

   /**
   * Get resellerAccountId
   * @return resellerAccountId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESELLER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResellerAccountId() {
    return resellerAccountId;
  }


  @JsonProperty(JSON_PROPERTY_RESELLER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResellerAccountId(String resellerAccountId) {
    this.resellerAccountId = resellerAccountId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateResaleAuthorizationChangeDetail createResaleAuthorizationChangeDetail = (CreateResaleAuthorizationChangeDetail) o;
    return Objects.equals(this.name, createResaleAuthorizationChangeDetail.name) &&
        Objects.equals(this.description, createResaleAuthorizationChangeDetail.description) &&
        Objects.equals(this.productId, createResaleAuthorizationChangeDetail.productId) &&
        Objects.equals(this.resellerAccountId, createResaleAuthorizationChangeDetail.resellerAccountId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, productId, resellerAccountId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateResaleAuthorizationChangeDetail {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    resellerAccountId: ").append(toIndentedString(resellerAccountId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

