/*
 * ResaleAuthorization_1_0_ChangeTypes
 *     Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.services.marketplacecatalog.model.resaleauthorization_1_0.changetypes;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.services.marketplacecatalog.model.resaleauthorization_1_0.changetypes.ResaleNetPaymentTermType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateNetPaymentTerm
 */
@JsonPropertyOrder({
  UpdateNetPaymentTerm.JSON_PROPERTY_TYPE,
  UpdateNetPaymentTerm.JSON_PROPERTY_PAYMENT_DUE_PERIOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UpdateNetPaymentTerm implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TYPE = "Type";
  private ResaleNetPaymentTermType type;

  public static final String JSON_PROPERTY_PAYMENT_DUE_PERIOD = "PaymentDuePeriod";
  private String paymentDuePeriod;

  public UpdateNetPaymentTerm() {
  }

  public UpdateNetPaymentTerm type(ResaleNetPaymentTermType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResaleNetPaymentTermType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(ResaleNetPaymentTermType type) {
    this.type = type;
  }

  public UpdateNetPaymentTerm paymentDuePeriod(String paymentDuePeriod) {
    
    this.paymentDuePeriod = paymentDuePeriod;
    return this;
  }

  /**
   * Get paymentDuePeriod
   * @return paymentDuePeriod
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_DUE_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPaymentDuePeriod() {
    return paymentDuePeriod;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_DUE_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentDuePeriod(String paymentDuePeriod) {
    this.paymentDuePeriod = paymentDuePeriod;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateNetPaymentTerm updateNetPaymentTerm = (UpdateNetPaymentTerm) o;
    return Objects.equals(this.type, updateNetPaymentTerm.type) &&
        Objects.equals(this.paymentDuePeriod, updateNetPaymentTerm.paymentDuePeriod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, paymentDuePeriod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateNetPaymentTerm {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    paymentDuePeriod: ").append(toIndentedString(paymentDuePeriod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

